---
- name: Create temp dir
  register: temp_dir
  command: mktemp -d
  become: yes
  become_user: ceph

- name: Fetch Ceph Monitor Keyring
  command: ceph auth get mon. -o mon_keyring_file
  args:
    chdir: "{{temp_dir.stdout}}"

- name: Fetch Ceph Monitor Mapfile
  command: ceph mon getmap -o mon_map_file
  args:
    chdir: "{{temp_dir.stdout}}"

- name: Check if node is already a Ceph Monitor
  command: monmaptool --print mon_map_file 
  args:
    chdir: "{{temp_dir.stdout}}"
  register: mon_result

- name: Create Ceph Monitor directory
  file: path="/var/lib/ceph/mon/ceph-{{ ansible_hostname }}" state=directory owner=ceph group=ceph

- name: Create Ceph Monitor
  command: ceph-mon -i "{{ ansible_hostname }}" --mkfs --monmap mon_map_file --keyring mon_keyring_file
  args:
    chdir: "{{temp_dir.stdout}}"
  become: yes
  become_user: ceph
  when: "'{{ ansible_hostname }}' not in mon_result.stdout"  

# This creates a running monitor on the right ip adress:
#- name: Start Ceph mon service
#  command: ceph-mon -i {{ ansible_hostname }} --public-addr {{ ansible_default_ipv4.address }}:{{ monitor_port }}
#  when: "'{{ ansible_hostname }}' not in mon_result.stdout"
#
# However, if we add:
#
# public_network = 10.64.22.162/27
# to
# /etc/ceph/ceph.conf
#
# systemd can start without running ceph-mon --public-addr at forehand.
# We will add that one to the common role when we will add the node role to it.
# Basically, removing ceph-deploy altogether...

- name: Create Systemd service
  service: name="ceph-mon@{{ ansible_hostname }}" state=started enabled=yes

- name: Remove temp dir
  file: name={{ temp_dir.stdout }} state=absent


