- name: install libselinux-python (needed for selinux with create repo)
  yum: state='present' name='libselinux-python'
- name: Config repo
  copy: src=ceph.repo dest=/etc/yum.repos.d/ceph.repo owner=root group=root mode=0644
- name: yum update
  yum: state='latest' name='*'
- name: install ceph-deploy
  yum: name='ceph-deploy' state='present' update_cache='yes'
