- name: create ceph user
  user: name=ceph comment="user for ceph" generate_ssh_key=yes
- name: copy ssh key to local temp folder
  fetch: src=/home/ceph/.ssh/id_rsa.pub dest="{{ hostvars['localhost']['mktemp']['stdout'] }}/{{ ansible_hostname }}.id_rsa.pub" flat=yes
- name: create /etc/ssh/ssh_known_hosts
  file: state=touch dest=/etc/ssh/ssh_known_hosts owner=root group=root mode=644
- name: add the nodes to known_hosts
  known_hosts: path='/etc/ssh/ssh_known_hosts'
               name="{{ item }}"
               key="{{ item }} ecdsa-sha2-nistp256 {{ hostvars[item]['ansible_ssh_host_key_ecdsa_public'] }}"
  with_items: "{{groups['NODES']}}"
