# This first step is important for 2 things:
# 1: gather facts of all hosts
# 2: apply all common stuff to all nodes
- hosts: OPENSTACK
  roles:
  - openstack-common

- hosts: OS-CNT
  roles:
  - controller

- hosts: OS-CMP
  roles:
  - compute

- hosts: OS-BLOCK
  roles:
  - block

- hosts: OS-OBJECT
  roles:
  - object

