---
- hosts:
  - localhost
  tasks:
  - name: Create local temp folder
    local_action: command mktemp -d
    register: mktemp

- hosts:
  - DEPLOY
  become: yes
  become_method: sudo
  roles:
  - deploy

- hosts:
  - NODES
  become: yes
  become_method: sudo
  roles:
  - node
