---

- hosts: all
  gather_facts: no
  tasks:
  - name: read facts
    setup:

- hosts:
  - localhost
  tasks:
  - name: Create local temp folder
    local_action: command mktemp -d
    register: mktemp

- hosts:
  - DEPLOY
  become: yes
  become_method: sudo
  roles:
  - deploy

- hosts:
  - localhost
  tasks:
  - name: Collect id_rsa.pubs
    shell: cat {{ mktemp.stdout }}/*
    register: id_rsa_pubs

- hosts:
  - all
  become: yes
  become_method: sudo
  roles:
  - common

- hosts:
  - NODES
  become: yes
  become_method: sudo
  roles:
  - node

- hosts:
  - localhost
  tasks:
  - name: Cleanup local temp folder
    file: state=absent dest={{ mktemp.stdout }}

