- name: create ceph user
  user: name=ceph comment="user for ceph" generate_ssh_key=yes
- name: grant sudo nopassword to ceph user
  copy: src='ceph.sudo' dest='/etc/sudoers.d/ceph' owner='root' group='root' mode=0440
- name: create authorized_keys
  file: state=touch dest=/home/ceph/.ssh/authorized_keys owner=ceph group=ceph mode=600
- name: set authorized_keys
  authorized_key: user=ceph key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}" 

