- name: add host to crush map
  command: ceph osd crush add-bucket "{{ ansible_host }}" host
  register: ceph_add_bucket

- name: move to default if newly added
  command: ceph osd crush move "{{ ansible_host }}" root=default
  when: '"already exists" not in ceph_add_bucket.stderr'

- name: setup disks 
  command: parted -s "/dev/{{ item.key }}" -- 'mklabel gpt mkpart "ceph data" xfs 1 -1'
  with_dict: "{{ ansible_devices }}" 
  when: 
  - item.value.removable == "0" 
  - item.value.partitions|length == 0

- name: find ceph partitions without xfs
  script: ceph_data_partitions_withoutXFS.py
  register: ceph_parts

- name: create xfs partitions
  filesystem: fstype=xfs dev="{{ item }}"
  with_items: "{{ ceph_parts.stdout_lines }}"

- name: find ceph filesystems not yet in fstab
  script: ceph_data_partitions_not_yet_in_fstab.py
  register: ceph_fss

- name: get osd num
  shell: ceph osd create
  with_items: "{{ ceph_fss.stdout_lines }}"
  register: osdnums

- name: mount new osds
  mount: name="/var/lib/ceph/osd/{{ ceph_cluster_name }}-{{ item.stdout }}/" src="{{ item.item }}" fstype=xfs state=mounted
  with_items: "{{ osdnums.results }}"

- name: find osd folders
  script: osds_by_folder.sh "/var/lib/ceph/osd/{{ ceph_cluster_name }}-"
  register: osds_by_folder

- name: check that the filesystems are correctly mounted
  script: check_osdnums_of_mounted_ceph_disks.sh "{{ ceph_cluster_name }}" "{{ item }}"
  with_items: "{{ osds_by_folder.stdout_lines }}"

- name: change ownership for new filesystems root dirs
  file: path="/var/lib/ceph/osd/{{ ceph_cluster_name }}-{{ item }}/" owner=ceph group=ceph state=directory
  with_items: "{{ osds_by_folder.stdout_lines }}"

- name: make osd structure inside osd fs
  command: ceph-osd -i "{{ item }}" --mkfs --mkkey
  args:
    creates: "/var/lib/ceph/osd/ceph-{{ item }}/ready"
  with_items: "{{ osds_by_folder.stdout_lines }}"
  become_user: ceph

- name: add osd auth to cluster
  command: ceph auth add "osd.{{ item }}" osd 'allow *' mon 'allow rwx' -i "/var/lib/ceph/osd/{{ ceph_cluster_name }}-{{ item }}/keyring"
  with_items: "{{ osds_by_folder.stdout_lines }}"
  
- name: add osd to crushmap
  command: ceph osd crush add "osd.{{ item }}" 1.0 host="{{ ansible_hostname }}"
  with_items: "{{ osds_by_folder.stdout_lines }}"

- name: create and enable service
  service: name="ceph-osd@{{ item }}" state=started enabled=yes
  with_items: "{{ osds_by_folder.stdout_lines }}"
