- name: find interfaces
  shell: ip route get {{item}} | sed -n '/dev/{s/.* dev //;s/ .*//;p}'
  with_items:
  - "{{public_nw}}"
  - "{{cluster_nw}}"
  register: ifaces
- name: configure iptables
  iptables: chain=INPUT destination_port={{item[1]}} in_interface={{item[0]['stdout']}} source={{item[0]['item']}} jump=ACCEPT protocol=tcp state=present
  with_nested:
  - ifaces.results
  - [ '{{monitor_port}}', '{{osd_start_port}}:{{osd_start_port+osd_daemons*4+osd_reservation}}' ]
- name: save iptables config
  shell: /usr/libexec/iptables/iptables.init save
