- name: install some packages that are needed for ceph
  yum: name={{ item }} state=present
  with_items:
  - ntp
  - ntpdate
  - ntp-doc

- name: update time
  command: ntpdate 10.64.225.20 && systemctl start ntpd
