# Using chrony is default for openstack mitaka deployment. Lets use it for both openstack and ceph...

- name: install some packages that are needed for ceph
  yum: name=chrony state=present

- name: copy chrony.conf
  template: src=chrony.conf dest=/etc/chrony.conf owner=root group=root mode=644
  register: chronyconf

- name: enable ntpd service
  service: name=chronyd enabled=yes state=started
