- name: Install EPEL repo
  yum:
    name: epel-release
    state: present
  when: ansible_distribution == "CentOS"
  register: epel_repo

- name: install libselinux-python (needed for selinux with create repo)
  yum: name=libselinux-python state=present

- name: yum update
  yum: state='latest' name='*'
  when: epel_repo|changed

- name: install some packages that are needed for ceph
  yum: name={{ item }} state=present
  with_items:
  - ntp
  - ntpdate
  - ntp-doc
  - iptables-services
