- name: Install EPEL repo
  yum:
    name: epel-release
    state: present
  when: ansible_distribution == "CentOS"

- name: install priorities package
  yum: name=yum-plugin-priorities state=present
