- name: Install EPEL repo
  yum:
    name: epel-release
    state: present
  when: ansible_distribution == "CentOS"
  register: epel_repo

- name: yum update
  yum: state='latest' name='*'
  when: epel_repo|changed

- name: install libselinux-python (needed for selinux with create repo)
  yum: name=libselinux-python state=present

- name: plaats Puppet repo file
  copy: src=puppetlabs.repo dest=/etc/yum.repos.d/puppetlabs-pc1.repo mode=644 owner=root group=root force=yes
  register: puppet_repo

- name: plaats Puppet GPG key file
  copy: src=puppetlabs_GPG.key dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-puppetlabs-PC1 mode=644 owner=root group=root force=yes
  register: puppet_gpg

- name: upgrade all packages
  yum: name=* state=latest
  when: ((puppet_repo|changed) or (puppet_gpg|changed))

- name: zet hostname
  command: /usr/bin/hostnamectl set-hostname {{ inventory_hostname }}

- name: import Puppetlabs GPG key
  rpm_key: state=present key=/etc/pki/rpm-gpg/RPM-GPG-KEY-puppetlabs-PC1

- name: install packages
  yum: name=puppet-agent state=installed

- name: start puppet service
  service: name=puppet state=started enabled=yes
